In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sqlite3

In [6]:
conn=sqlite3.connect('customer_churn.db')
sql_query="""
SELECT name
FROM sqlite_master
WHERE type='table'
"""

tables=pd.read_sql(sql_query,conn)

In [7]:
for table_name in tables['name']:
    df=pd.read_sql(f"Select*from {table_name}",conn)
    globals()[f"df_{table_name}"]=df
    print(f"created dataframe: df_{table_name}")

conn.close()

created dataframe: df_db_customer
created dataframe: df_db_subscription
created dataframe: df_db_support

In [8]:
df_db_customer.head()

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00,travel,None
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00,None,None
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00,movie,None
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00,None,None
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00,drama,None

In [9]:
df_db_customer.rename(columns={'name':'customer_name'}, inplace=True)

In [10]:
df_db_customer.drop(df_db_customer.columns[-2:],axis=1,inplace=True)

In [11]:
df_db_customer

,customerid,customer_name,country,state,gender,dob
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12 00:00:00
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23 00:00:00
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15 00:00:00
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30 00:00:00
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05 00:00:00
5,0013-MHZWF,durga,None,Delhi,Women,1988-12-10 00:00:00
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21 00:00:00
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14 00:00:00
8,0015-UOCOJ,maya,None,Kathmandu,Women,1985-07-07 00:00:00
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29 00:00:00
10,0017-DINOC,shiva,India,Maharashtra,Men,1997-01-22 00:00:00
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18 00:00:00
12,0018-NYROU,chitra,None,Telangana,Female,2004-12-01 00:00:00
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25 00:00:00
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11 00:00:00
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28 00:00:00
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19 00:00:00
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02 00:00:00
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30 00:00:00
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14 00:00:00
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06 00:00:00

In [12]:
df_db_customer['dob']=pd.to_datetime(df_db_customer['dob'])

In [13]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     object
 1   customer_name  21 non-null     object
 2   country        18 non-null     object
 3   state          21 non-null     object
 4   gender         21 non-null     object
 5   dob            21 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 1.1+ KB

In [14]:
df_db_customer['gender'].unique()

array(['Male', 'Female', 'Women', 'Men'], dtype=object)

In [15]:
df_db_customer['gender']=df_db_customer['gender'].replace({'Men':'Male','Women':'Female'})

In [16]:
df_db_customer['gender'].unique()

array(['Male', 'Female'], dtype=object)

In [17]:
state_counntry_mapping=df_db_customer.dropna(subset=['country']).set_index('state')['country'].to_dict()

df_db_customer['country']=df_db_customer['country'].fillna(df_db_customer['state'].map(state_counntry_mapping))

In [18]:
df_db_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customerid     21 non-null     object
 1   customer_name  21 non-null     object
 2   country        21 non-null     object
 3   state          21 non-null     object
 4   gender         21 non-null     object
 5   dob            21 non-null     datetime64[ns]
dtypes: datetime64[ns](1), object(5)
memory usage: 1.1+ KB

In [19]:
date_col=['subscription_start_date','renewal_date','cancellation_date']

df_db_subscription[date_col]=df_db_subscription[date_col].apply(pd.to_datetime)
df_db_subscription.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21 entries, 0 to 20
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   customerid               21 non-null     object
 1   subscription_start_date  21 non-null     datetime64[ns]
 2   subscription_type        21 non-null     object
 3   renewal_date             21 non-null     datetime64[ns]
 4   plan_type                21 non-null     object
 5   contract_type            21 non-null     object
 6   cancellation_date        6 non-null      datetime64[ns]
 7   cancellation_reason      6 non-null      object
 8   monthly_charges          21 non-null     float64
 9   cltv                     21 non-null     int64
 10  churn_score              21 non-null     int64
dtypes: datetime64[ns](3), float64(1), int64(2), object(5)
memory usage: 1.9+ KB

In [20]:
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      object
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
 4   col_1           0 non-null      object
 5   comment         4 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [21]:
df_db_support.drop(columns=['col_1','comment'],inplace=True)

In [22]:
df_db_support

   customerid       complaint_date escalations  csat_score
0  0003-MKNFE  2024-08-28 00:00:00           N          60
1  0003-MKNFE  2024-08-28 00:00:00           Y          10
2  0013-EXCHZ  2024-01-20 00:00:00           Y          20
3  0013-MHZWF  2025-03-18 00:00:00           N          90
4  0013-SMEOE  2024-11-01 00:00:00           N          30
5  0017-IUDMW  2024-04-10 00:00:00           Y          25
6  0019-EFAEP  2024-09-27 00:00:00           Y          30
7  0022-TCJCI  2024-09-13 00:00:00           Y          10
8  0022-TCJCI  2024-09-14 00:00:00           N          90

In [23]:
df_db_support['complaint_date']=pd.to_datetime(df_db_support['complaint_date'])

In [24]:
df_db_support.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customerid      9 non-null      object
 1   complaint_date  9 non-null      datetime64[ns]
 2   escalations     9 non-null      object
 3   csat_score      9 non-null      int64
dtypes: datetime64[ns](1), int64(1), object(2)
memory usage: 420.0+ bytes

In [25]:
## Feature Engineering and Data Analysis

In [26]:
df_db_subscription['churn_flag']=np.where(df_db_subscription['cancellation_date'].notna(),1,0)

In [27]:
df_db_subscription.head()

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score,churn_flag
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,None,13.99,627,12,0
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,None,6.99,210,34,0
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,None,22.99,1725,8,0
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88,1

In [28]:
df_db_subscription.merge(df_db_customer,on='customerid',how='left')

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score,churn_flag,customer_name,country,state,gender,dob
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,None,13.99,627,12,0,keshav,India,Maharashtra,Male,1982-04-12
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1,raghav,India,Karnataka,Male,1995-11-23
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,None,6.99,210,34,0,lalita,India,Delhi,Female,1978-02-15
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,None,22.99,1725,8,0,mohan,India,Nagaland,Male,2001-08-30
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88,1,mira,India,Delhi,Female,1990-05-05
5,0013-MHZWF,2022-06-18,Paid,2025-06-18,Standard,Annual,NaT,None,17.99,720,22,0,durga,India,Delhi,Female,1988-12-10
6,0013-SMEOE,2021-09-30,Refferal,2024-09-30,Basic,Monthly,2024-11-15,Not enough content,8.99,230,79,1,mina,India,Meghalaya,Female,1976-09-21
7,0014-BMAQU,2020-02-14,Organic,2025-02-14,Premium,Annual,NaT,None,22.99,1840,5,0,madan,India,Rajasthan,Male,1999-03-14
8,0015-UOCOJ,2023-07-22,Organic,2024-07-22,Standard,Monthly,NaT,None,13.99,240,34,0,maya,Nepal,Kathmandu,Female,1985-07-07
9,0016-QLJIS,2022-04-03,Organic,2025-04-03,Basic,Annual,NaT,None,6.99,335,41,0,arjun,Nepal,Kathmandu,Male,1993-10-29
10,0017-DINOC,2021-12-01,Organic,2025-12-01,Premium,Annual,NaT,None,22.99,1610,14,0,shiva,India,Maharashtra,Male,1997-01-22
11,0017-IUDMW,2023-03-17,Refferal,2024-03-17,Standard,Monthly,2024-05-01,Poor streaming quality,7.99,270,83,1,rangadevi,India,Karnataka,Female,1981-06-18
12,0018-NYROU,2020-10-09,Organic,2025-10-09,Standard,Annual,NaT,None,13.99,980,19,0,chitra,India,Telangana,Female,2004-12-01
13,0019-EFAEP,2022-08-25,Refferal,2024-08-25,Basic,Monthly,2024-10-31,Switched to competitor,12.99,160,76,1,raju,India,Meghalaya,Female,1992-04-25
14,0019-GFNTW,2019-11-11,Paid,2025-11-11,Premium,Annual,NaT,None,92.99,2185,3,0,Madhav,India,Uttar Pradesh,Male,1979-11-11
15,0020-INWCK,2023-05-06,Organic,2025-05-06,Standard,Monthly,NaT,None,13.99,640,58,0,parvati,India,Delhi,Female,1986-02-28
16,0020-JDNXP,2022-01-19,Organic,2024-01-19,Premium,Annual,NaT,None,20.99,550,62,0,rikim,India,Meghalaya,Female,1994-08-19
17,0021-IKXGC,2021-07-07,Paid,2025-07-07,Standard,Annual,NaT,None,13.99,840,27,0,vishakha,India,Rajasthan,Female,2000-09-02
18,0022-TCJCI,2023-09-14,Refferal,2024-09-14,Basic,Monthly,2024-09-14,Forgot to cancel trial,16.99,42,99,1,raghvendra,India,Telangana,Male,1983-12-30
19,0023-HGHWL,2020-06-23,Organic,2025-06-23,Premium,Annual,NaT,None,22.99,1955,7,0,rishabh,India,Uttar Pradesh,Male,1991-05-14
20,0023-UYUPN,2022-12-31,Paid,2025-12-31,Standard,Monthly,NaT,None,13.99,790,47,0,sudevi,India,Maharashtra,Female,1977-10-06

In [29]:
df=df_db_subscription.merge(df_db_customer,on='customerid',how='left')
df_db_subscription.merge(df_db_support,on='customerid',how='left')

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score,churn_flag,complaint_date,escalations,csat_score
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,None,13.99,627,12,0,NaT,NaN,NaN
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1,2024-08-28,N,60.0
2,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1,2024-08-28,Y,10.0
3,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,None,6.99,210,34,0,NaT,NaN,NaN
4,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,None,22.99,1725,8,0,NaT,NaN,NaN
5,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88,1,2024-01-20,Y,20.0
6,0013-MHZWF,2022-06-18,Paid,2025-06-18,Standard,Annual,NaT,None,17.99,720,22,0,2025-03-18,N,90.0
7,0013-SMEOE,2021-09-30,Refferal,2024-09-30,Basic,Monthly,2024-11-15,Not enough content,8.99,230,79,1,2024-11-01,N,30.0
8,0014-BMAQU,2020-02-14,Organic,2025-02-14,Premium,Annual,NaT,None,22.99,1840,5,0,NaT,NaN,NaN
9,0015-UOCOJ,2023-07-22,Organic,2024-07-22,Standard,Monthly,NaT,None,13.99,240,34,0,NaT,NaN,NaN
10,0016-QLJIS,2022-04-03,Organic,2025-04-03,Basic,Annual,NaT,None,6.99,335,41,0,NaT,NaN,NaN
11,0017-DINOC,2021-12-01,Organic,2025-12-01,Premium,Annual,NaT,None,22.99,1610,14,0,NaT,NaN,NaN
12,0017-IUDMW,2023-03-17,Refferal,2024-03-17,Standard,Monthly,2024-05-01,Poor streaming quality,7.99,270,83,1,2024-04-10,Y,25.0
13,0018-NYROU,2020-10-09,Organic,2025-10-09,Standard,Annual,NaT,None,13.99,980,19,0,NaT,NaN,NaN
14,0019-EFAEP,2022-08-25,Refferal,2024-08-25,Basic,Monthly,2024-10-31,Switched to competitor,12.99,160,76,1,2024-09-27,Y,30.0
15,0019-GFNTW,2019-11-11,Paid,2025-11-11,Premium,Annual,NaT,None,92.99,2185,3,0,NaT,NaN,NaN
16,0020-INWCK,2023-05-06,Organic,2025-05-06,Standard,Monthly,NaT,None,13.99,640,58,0,NaT,NaN,NaN
17,0020-JDNXP,2022-01-19,Organic,2024-01-19,Premium,Annual,NaT,None,20.99,550,62,0,NaT,NaN,NaN
18,0021-IKXGC,2021-07-07,Paid,2025-07-07,Standard,Annual,NaT,None,13.99,840,27,0,NaT,NaN,NaN
19,0022-TCJCI,2023-09-14,Refferal,2024-09-14,Basic,Monthly,2024-09-14,Forgot to cancel trial,16.99,42,99,1,2024-09-13,Y,10.0
20,0022-TCJCI,2023-09-14,Refferal,2024-09-14,Basic,Monthly,2024-09-14,Forgot to cancel trial,16.99,42,99,1,2024-09-14,N,90.0
21,0023-HGHWL,2020-06-23,Organic,2025-06-23,Premium,Annual,NaT,None,22.99,1955,7,0,NaT,NaN,NaN
22,0023-UYUPN,2022-12-31,Paid,2025-12-31,Standard,Monthly,NaT,None,13.99,790,47,0,NaT,NaN,NaN

In [30]:
df.shape

(21, 17)

In [31]:
df_db_subscription.shape

(21, 12)

In [32]:
df_db_subscription['customerid'].nunique()

21

In [33]:
df_db_customer['customerid'].nunique()

21

In [34]:
df_db_support['customerid'].nunique()

7

In [35]:
df_db_support['customerid'].size

9

In [36]:
df_db_support

   customerid complaint_date escalations  csat_score
0  0003-MKNFE     2024-08-28           N          60
1  0003-MKNFE     2024-08-28           Y          10
2  0013-EXCHZ     2024-01-20           Y          20
3  0013-MHZWF     2025-03-18           N          90
4  0013-SMEOE     2024-11-01           N          30
5  0017-IUDMW     2024-04-10           Y          25
6  0019-EFAEP     2024-09-27           Y          30
7  0022-TCJCI     2024-09-13           Y          10
8  0022-TCJCI     2024-09-14           N          90

In [37]:
df_db_support['Complaint_Count']=df_db_support.groupby('customerid')['customerid'].transform('count')

In [38]:
df_db_support=df_db_support.sort_values('complaint_date').drop_duplicates('customerid',keep='last')

In [39]:
df_db_support

   customerid complaint_date escalations  csat_score  Complaint_Count
2  0013-EXCHZ     2024-01-20           Y          20                1
5  0017-IUDMW     2024-04-10           Y          25                1
1  0003-MKNFE     2024-08-28           Y          10                2
8  0022-TCJCI     2024-09-14           N          90                2
6  0019-EFAEP     2024-09-27           Y          30                1
4  0013-SMEOE     2024-11-01           N          30                1
3  0013-MHZWF     2025-03-18           N          90                1

In [40]:
df=df_db_subscription.merge(df_db_customer,on='customerid',how='left')
df_db_subscription.merge(df_db_support,on='customerid',how='left')

,customerid,subscription_start_date,subscription_type,renewal_date,plan_type,contract_type,cancellation_date,cancellation_reason,monthly_charges,cltv,churn_score,churn_flag,complaint_date,escalations,csat_score,Complaint_Count
0,0002-ORFBO,2021-03-15,Refferal,2025-03-15,Standard,Annual,NaT,None,13.99,627,12,0,NaT,NaN,NaN,NaN
1,0003-MKNFE,2020-08-01,Paid,2024-08-01,Premium,Annual,2024-09-10,Switched to competitor,12.99,1150,91,1,2024-08-28,Y,10.0,2.0
2,0004-TLHLJ,2022-11-20,Organic,2025-11-20,Basic,Monthly,NaT,None,6.99,210,34,0,NaT,NaN,NaN,NaN
3,0011-IGKFF,2019-05-10,Paid,2025-05-10,Premium,Annual,NaT,None,22.99,1725,8,0,NaT,NaN,NaN,NaN
4,0013-EXCHZ,2023-01-05,Refferal,2024-01-05,Standard,Monthly,2024-02-28,Too expensive,13.99,195,88,1,2024-01-20,Y,20.0,1.0
5,0013-MHZWF,2022-06-18,Paid,2025-06-18,Standard,Annual,NaT,None,17.99,720,22,0,2025-03-18,N,90.0,1.0
6,0013-SMEOE,2021-09-30,Refferal,2024-09-30,Basic,Monthly,2024-11-15,Not enough content,8.99,230,79,1,2024-11-01,N,30.0,1.0
7,0014-BMAQU,2020-02-14,Organic,2025-02-14,Premium,Annual,NaT,None,22.99,1840,5,0,NaT,NaN,NaN,NaN
8,0015-UOCOJ,2023-07-22,Organic,2024-07-22,Standard,Monthly,NaT,None,13.99,240,34,0,NaT,NaN,NaN,NaN
9,0016-QLJIS,2022-04-03,Organic,2025-04-03,Basic,Annual,NaT,None,6.99,335,41,0,NaT,NaN,NaN,NaN
10,0017-DINOC,2021-12-01,Organic,2025-12-01,Premium,Annual,NaT,None,22.99,1610,14,0,NaT,NaN,NaN,NaN
11,0017-IUDMW,2023-03-17,Refferal,2024-03-17,Standard,Monthly,2024-05-01,Poor streaming quality,7.99,270,83,1,2024-04-10,Y,25.0,1.0
12,0018-NYROU,2020-10-09,Organic,2025-10-09,Standard,Annual,NaT,None,13.99,980,19,0,NaT,NaN,NaN,NaN
13,0019-EFAEP,2022-08-25,Refferal,2024-08-25,Basic,Monthly,2024-10-31,Switched to competitor,12.99,160,76,1,2024-09-27,Y,30.0,1.0
14,0019-GFNTW,2019-11-11,Paid,2025-11-11,Premium,Annual,NaT,None,92.99,2185,3,0,NaT,NaN,NaN,NaN
15,0020-INWCK,2023-05-06,Organic,2025-05-06,Standard,Monthly,NaT,None,13.99,640,58,0,NaT,NaN,NaN,NaN
16,0020-JDNXP,2022-01-19,Organic,2024-01-19,Premium,Annual,NaT,None,20.99,550,62,0,NaT,NaN,NaN,NaN
17,0021-IKXGC,2021-07-07,Paid,2025-07-07,Standard,Annual,NaT,None,13.99,840,27,0,NaT,NaN,NaN,NaN
18,0022-TCJCI,2023-09-14,Refferal,2024-09-14,Basic,Monthly,2024-09-14,Forgot to cancel trial,16.99,42,99,1,2024-09-14,N,90.0,2.0
19,0023-HGHWL,2020-06-23,Organic,2025-06-23,Premium,Annual,NaT,None,22.99,1955,7,0,NaT,NaN,NaN,NaN
20,0023-UYUPN,2022-12-31,Paid,2025-12-31,Standard,Monthly,NaT,None,13.99,790,47,0,NaT,NaN,NaN,NaN

In [41]:
df.shape

(21, 17)

In [42]:
df_db_subscription.shape

(21, 12)

In [43]:
df.to_csv('exp_churn_data.csv',index=False)

In [44]:
df.columns

Index(['customerid', 'subscription_start_date', 'subscription_type',
       'renewal_date', 'plan_type', 'contract_type', 'cancellation_date',
       'cancellation_reason', 'monthly_charges', 'cltv', 'churn_score',
       'churn_flag', 'customer_name', 'country', 'state', 'gender', 'dob'],
      dtype='object')

In [45]:
## Data Analysis

In [46]:
Churn_rate=df['churn_flag'].mean()*100
print("Churn_rate=",round(Churn_rate,2),"%")

Churn_rate= 28.57 %

In [47]:
retention_rate=100-Churn_rate

In [48]:
print("retention_rate=",round(retention_rate,2),"%")

retention_rate= 71.43 %

In [49]:
churn_by_plan=(df.groupby('plan_type')['churn_flag'].mean().mul(100).round(2).reset_index(name='churn_rate_pct'))
print("Churn by plan=",churn_by_plan)

Churn by plan=   plan_type  churn_rate_pct
0     Basic           60.00
1   Premium           14.29
2  Standard           22.22

In [50]:
#Avg Revenue Per Year (ARPU)
arpu=df['monthly_charges'].mean()
print('ARPU=',round(arpu,2))

ARPU= 18.85

In [51]:
#Avg Customer Tenure
today=pd.Timestamp.today()

df['tenure_days']=np.where(
    df['cancellation_date'].notna(),
    (df['cancellation_date']-df['subscription_start_date']).dt.days,
    (today-df['subscription_start_date']).dt.days
) 

avg_tenure=df['tenure_days'].mean()
print("Avg tenure days=",round(avg_tenure,0))

Avg tenure days= 1489.0

In [52]:
#Revenue at risk
revenue_at_risk=df.loc[df['churn_flag']==1,'monthly_charges'].sum()
print("Revenue at risk (Rs K)=",revenue_at_risk)

Revenue at risk (Rs K)= 73.94

In [56]:
df.to_csv('customer_churn_analysis',index=False)